# Generated by Django 6.0.5 on 2026-05-27 13:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Monto en Bs que el usuario quiere cobrar', max_digits=12)),
                ('amount_to_pay', models.DecimalField(blank=True, decimal_places=2, help_text='Monto exacto a pagar (ZAS suma centavos como ID; MSC = requested)', max_digits=12, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('creating', 'Generando'), ('pending', 'Esperando pago'), ('paid', 'Pagado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('failed', 'Fallido')], default='creating', max_length=20)),
                ('provider', models.CharField(blank=True, default='', help_text='Provider activo: msc | zas | ...', max_length=20)),
                ('validation_method', models.CharField(blank=True, default='', help_text='token_concept (MSC) | amount_decimals (ZAS)', max_length=30)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('code', models.CharField(blank=True, default='', help_text='Codigo visible (concepto/motivo del QR)', max_length=16)),
                ('qr_payload', models.TextField(blank=True, default='', help_text='Texto del QR para renderizar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_seconds', models.FloatField(default=0.0, help_text='ETA para que el QR este listo (si CREATING)')),
                ('error', models.TextField(blank=True, default='')),
                ('notification', models.JSONField(blank=True, null=True)),
                ('attempts', models.JSONField(blank=True, default=list, help_text='Lista de intentos por provider con resultado')),
                ('batch_id', models.UUIDField(blank=True, db_index=True, help_text='Agrupa varios QR creados juntos', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='qrgen_payme_status_ef74c8_idx'), models.Index(fields=['provider'], name='qrgen_payme_provide_36bd80_idx'), models.Index(fields=['created_at'], name='qrgen_payme_created_07a0f9_idx')],
            },
        ),
    ]
